# Generated by Django 3.0.7 on 2020-06-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_live_link',
            field=models.URLField(default='enter live link', max_length=100000),
        ),
    ]
